version: '3'
services:
  db:
    image: postgres:9
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_volume:/var/lib/postgresql/data
  
  redis:
    image: redis:7.0
    ports:
      - "6379:6379"
    volumes:
      - redis_volume:/data

  web:
    build: .
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    restart: always
    tty: true
    stdin_open: true
    depends_on:
      - db
      - redis

volumes:
  postgres_volume:
  redis_volume:
