version: '3'
services:
  db:
    image: postgres:9
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_volume:/var/lib/postgresql/data
  
  redis:
    image: redis:7.0
    ports:
      - "6379:6379"
    volumes:
      - redis_volume:/data

  chrome:
    image: seleniarm/standalone-chromium:113.0
    shm_size: '256mb'
    ports:
      - '4444:4444'

  web:
    build: .
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      SELENIUM_DRIVER_URL: http://chrome:4444/wd/hub
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    restart: always
    tty: true
    stdin_open: true
    depends_on:
      - db
      - redis
      - chrome

volumes:
  postgres_volume:
  redis_volume:
